name: Laravel Pint (Simple)

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - 'pint.json'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - 'pint.json'

jobs:
  pint:
    name: Laravel Pint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo, phar, tokenizer, xml, xmlwriter, zip

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Run Laravel Pint (check mode)
        run: vendor/bin/pint --test

      - name: Run Laravel Pint (format mode)
        if: github.event_name == 'push'
        run: vendor/bin/pint

      - name: Commit changes (if any)
        if: github.event_name == 'push'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Apply Laravel Pint fixes"
          git push 